#!/usr/bin/env python3
"""
fetch_pl_photos.py

Fetches all Premier League player IDs across every season (1992/93 to present)
from the official PL API, then outputs a JS file mapping normalised player names
to their PL player IDs.

Photo URL:
  https://resources.premierleague.com/premierleague/photos/players/110x140/p{id}.png

Players without a photo on the CDN return 404, which game.js catches via onerror
and falls back to the grey silhouette.

Outputs: data/pl_photo_ids.js

Usage:
    python3 fetch_pl_photos.py

Run time: ~3-5 minutes (rate-limited; ~100 API calls across 34 seasons).
Safe to re-run — just overwrites the output file.
"""

import json
import time
import unicodedata
import requests

# ── All PL seasons ────────────────────────────────────────────────────────
SEASONS = [
    (1,   "1992/93"), (2,   "1993/94"), (3,   "1994/95"), (4,   "1995/96"),
    (5,   "1996/97"), (6,   "1997/98"), (7,   "1998/99"), (8,   "1999/00"),
    (9,   "2000/01"), (10,  "2001/02"), (11,  "2002/03"), (12,  "2003/04"),
    (13,  "2004/05"), (14,  "2005/06"), (15,  "2006/07"), (16,  "2007/08"),
    (17,  "2008/09"), (18,  "2009/10"), (19,  "2010/11"), (20,  "2011/12"),
    (21,  "2012/13"), (22,  "2013/14"), (27,  "2014/15"), (42,  "2015/16"),
    (54,  "2016/17"), (79,  "2017/18"), (210, "2018/19"), (274, "2019/20"),
    (363, "2020/21"), (418, "2021/22"), (489, "2022/23"), (578, "2023/24"),
    (719, "2024/25"), (777, "2025/26"),
]

HEADERS = {
    'Origin':     'https://www.premierleague.com',
    'Referer':    'https://www.premierleague.com/',
    'User-Agent': 'Mozilla/5.0 (compatible; StatpadSoccer/1.0)',
}
PAGE_SIZE     = 100
REQUEST_DELAY = 0.4   # seconds between API calls
OUTPUT_FILE   = 'data/pl_photo_ids.js'


# ── Name normalisation (mirrors game.js normName) ────────────────────────
def norm_name(name):
    name = name.replace('ø', 'o').replace('Ø', 'O')
    name = name.replace('æ', 'ae').replace('Æ', 'AE')
    name = name.replace('œ', 'oe').replace('Œ', 'OE')
    name = name.replace('ð', 'd').replace('Ð', 'D')
    name = name.replace('þ', 'th').replace('Þ', 'TH')
    name = name.replace('ß', 'ss')
    name = name.replace('ł', 'l').replace('Ł', 'L')
    name = name.replace('đ', 'd').replace('Đ', 'D')
    nfkd = unicodedata.normalize('NFD', name)
    return ''.join(c for c in nfkd if unicodedata.category(c) != 'Mn').lower().strip()


# ── Fetch one season's worth of players ─────────────────────────────────
def fetch_season(season_id, season_label):
    """Returns dict: normed_name -> (player_id, display_name)"""
    found = {}
    page  = 0

    while True:
        url = (
            f'https://footballapi.pulselive.com/football/players'
            f'?pageSize={PAGE_SIZE}&compSeasons={season_id}&page={page}'
        )
        try:
            r = requests.get(url, headers=HEADERS, timeout=15)
            r.raise_for_status()
            data = r.json()
        except Exception as e:
            print(f'\n  [error season {season_label} page {page}: {e}]')
            break

        content = data.get('content', [])
        if not content:
            break

        for p in content:
            pid  = p.get('playerId')
            name = (p.get('name') or {}).get('display', '')
            if pid and name:
                normed = norm_name(name)
                # If we've seen this normed name before, prefer the higher player ID
                # (higher IDs tend to be more recently registered = canonical record)
                if normed not in found or pid > found[normed][0]:
                    found[normed] = (pid, name)

        # Pagination
        page_info = data.get('pageInfo', {})
        total = page_info.get('numEntries', 0)
        if (page + 1) * PAGE_SIZE >= total:
            break

        page += 1
        time.sleep(REQUEST_DELAY)

    return found


# ── Write output JS ──────────────────────────────────────────────────────
def write_output(players):
    lines = [
        '/* pl_photo_ids.js',
        '   AUTO-GENERATED by fetch_pl_photos.py — do not edit by hand.',
        '   Maps normalised player names to Premier League player IDs.',
        '   Photo URL: https://resources.premierleague.com/premierleague/photos/players/110x140/p{id}.png',
        '   Players without a CDN photo return 404; game.js falls back to silhouette.',
        '*/',
        '(function () {',
        '  window.PL_PLAYER_IDS = {',
    ]
    for normed in sorted(players.keys()):
        pid = players[normed][0]
        escaped = normed.replace("'", "\\'")
        lines.append(f"    '{escaped}': {pid},")
    lines.append('  };')
    lines.append('})();')

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


# ── Main ─────────────────────────────────────────────────────────────────
def main():
    all_players = {}  # normed_name -> (player_id, display_name)

    for season_id, season_label in SEASONS:
        print(f'  {season_label} (ID {season_id})... ', end='', flush=True)
        season_players = fetch_season(season_id, season_label)

        new = 0
        for normed, (pid, name) in season_players.items():
            if normed not in all_players:
                all_players[normed] = (pid, name)
                new += 1
            elif pid > all_players[normed][0]:
                all_players[normed] = (pid, name)

        print(f'{len(season_players)} players  (+{new} new)  [total {len(all_players)}]')
        time.sleep(REQUEST_DELAY)

    write_output(all_players)
    print(f'\nWrote {len(all_players)} entries to {OUTPUT_FILE}')
    print('Next: commit data/pl_photo_ids.js and deploy.')


if __name__ == '__main__':
    main()
