#!/usr/bin/env python3
"""
fix_double_count.py

One-time patch for the existing players.json / players_data.js data.

Bug: when a player transferred mid-season, season-total stats (goals,
assists, etc.) were stored on EVERY club entry for that season, causing
double- or triple-counting in career totals.

Fix: for each player, for every season year where they have more than one
club entry, assign the season-total stats to the primary club (most apps)
and zero them out on all secondary entries.

Apps and clean_sheets are already stored per-club correctly and are NOT
changed.

Usage:
    python3 fix_double_count.py
"""

import json, os

DATA_DIR  = "data"
JSON_FILE = os.path.join(DATA_DIR, "players.json")
JS_FILE   = os.path.join(DATA_DIR, "players_data.js")

# Stats that were fetched as season totals (not per-club) and need deduping.
SEASON_TOTAL_STATS = [
    "goals", "assists", "yellow_cards", "red_cards", "shots",
    "saves", "tackles_won", "interceptions", "clearances",
    "big_chances_created", "penalties_scored", "hit_woodwork",
    "accurate_passes",
]


def fix_player(player):
    seasons = player.get("seasons", [])
    if not seasons:
        return 0

    # Group season entries by seasonYear
    from collections import defaultdict
    by_year = defaultdict(list)
    for s in seasons:
        by_year[s["seasonYear"]].append(s)

    fixed = 0
    for year, entries in by_year.items():
        if len(entries) <= 1:
            continue  # no transfer that season — nothing to fix

        # Find primary club (most apps; first wins ties)
        primary = max(entries, key=lambda e: e.get("apps", 0))

        for entry in entries:
            if entry is primary:
                continue
            # Zero out season-total stats on secondary clubs
            for stat in SEASON_TOTAL_STATS:
                if entry.get(stat, 0) != 0:
                    entry[stat] = 0
                    fixed += 1

    return fixed


def main():
    print(f"Loading {JSON_FILE}…")
    with open(JSON_FILE, encoding="utf-8") as f:
        payload = json.load(f)

    players = payload.get("players", [])
    print(f"  {len(players)} players loaded")

    total_fixed = 0
    affected_players = 0
    for player in players:
        n = fix_player(player)
        if n:
            affected_players += 1
            total_fixed += n

    print(f"  Fixed {total_fixed} stat values across {affected_players} players")

    # Update timestamp
    payload["generated"] = payload.get("generated", "") + " (patched by fix_double_count.py)"
    payload["total_players"] = len(players)

    print(f"Writing {JSON_FILE}…")
    with open(JSON_FILE, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    print(f"Writing {JS_FILE}…")
    with open(JS_FILE, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scraper.py */\n")
        f.write(f"window.PLAYERS_DATA = {json.dumps(payload, ensure_ascii=False)};\n")

    print("Done. Deploy players_data.js to apply the fix.")


if __name__ == "__main__":
    main()
